### ISSUE TITLE
bug: querying index seems to be different between PouchDB and CouchDB

### ISSUE THREAD

**Issue by TillaTheHun0** [hyper63/hyper-adapter-pouchdb#25]
TODO: there seems some differences between Pouch And Couch on how indexes are handled. See https://github.com/pouchdb/pouchdb/issues/8385.

> There is a different behaviour between PouchDB and CouchDB when querying multi-fields index on a selector that does not include all the indexed fields.
With PouchDB, it is expected that all the indexed fields exist in the selector, otherwise an error is returned.
With CouchDB, it is expected that all the indexed fields exist in the selector OR in the sort. Typically, with a ['foo', 'bar'] index, it is accepted to execute a find query with a selector including only bar, as long as foo is expressed in the sort.

Because of this, the sort query test in hyper-test is not passing. Will need to solve this in PouchDB I think

**Comment by TillaTheHun0** [comment]
Perhaps this will be solved when using the `indexeddb` adapter https://pouchdb.com/2020/02/12/pouchdb-7.2.0.html which is now included in the [Pouch default distribution](https://github.com/pouchdb/pouchdb/releases/tag/7.3.0)

Looks like there are intentions to port over to Deno Pouch in https://github.com/aaronhuggins/pouchdb_deno/issues/8

**Comment by aaronhuggins** [comment]
This bug is actually kind-of a big deal for implementing pouchdb-server in Deno.

**Comment by aaronhuggins** [comment]
@TillaTheHun0 I released v2 with PouchDB 7.3.0; it ships with the `indexeddb` adapter.

**Comment by TillaTheHun0** [comment]
@aaronhuggins The `indexeddb` adapter works and passes all the tests that `idb` does 👍! but it also fails all the tests the `idb` does. So it seems the discrepancy with querying an index between Couch and Pouch isn't solved in `indexeddb` adapter. *Le Sigh*

Regardless, we still upgraded to PouchDB 7.3.0 and exposed the `indexeddb` option on the adapter. Thank you!

**Comment by TillaTheHun0** [comment]
I managed to put a hack in place to get around this issue in https://github.com/hyper63/hyper-adapter-pouchdb/pull/31

@aaronhuggins can you think of any potential pitfalls in that approach?

**Comment by aaronhuggins** [comment]
No glaring issues stand out to me. Might technically add further re-iteration, but likely not a huge performance hit as it's in-memory at that point on not a disk io issue.
